name: 'PR Gatekeeper'
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  create_pending_check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Creates pending status check'
        run: |
          curl --request POST \
          --url "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }}" \
          --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --header "Accept: application/vnd.github.v3+json" \
          --data '{
            "state": "failure",
            "description": "Aguardando execução do CI manual para validar as alterações.",
            "context": "Verificacao Manual CI"
          }'
